cache:
  paths:
    - node_modules/

before_script:
  - composer install --prefer-dist --no-interaction -o > /dev/null
  - cp .env.example .env
  - php artisan key:generate
  - /home/gitlabci/gitlabci_vukcore.sh
  - php artisan migrate -vvv
  - php artisan module:migrate -vvv
  - php artisan serve -q &

phpunit:php5.6:mysql5.5:
  image: php:5.6
  services:
    - mysql:5.5
  only:
    - development
    - production
    - release/*
  script:
    - npm install gulp > /dev/null
    - npm install > /dev/null
    - gulp --production
    - php vendor/bin/phpunit  --coverage-text --colors=never
    
phpcs:php5.6:mysql5.5:
  image: php:5.6
  services:
    - mysql:5.5
  only:
    - development
    - production
    - release/*
  script:
    - phpcs "--standard=PSR2" "--report=full" "--extensions=inc,php,phpt,php4,php5,php3,phtml" "--encoding=UTF-8" "--ignore=blade.php,*/Tests/*,*/Database/Migrations/*" -p -v app/
