before_script:
  - composer install --prefer-dist > /dev/null
  - npm install gulp > /dev/null
  - gulp --production
  - cp .example.env .env
  - php artisan key:generate
  - php artisan migrate

phpunit:php5.5:mysql5.5:
  image: php:5.5
  services:
    - mysql:5.5
  only:
    - development
    - production
  script:
    - php vendor/bin/phpunit --colors
    - vendor/bin/phpmd app/ text phpmd.xml
    - vendor/bin/phpcs --standard=psr2 app
  tags:
    - production
    - development