preset: laravel

risky: false

enabled:
    - "unalign_double_arrow"
    - "alpha_ordered_imports"

disabled:
    - "not_operator_with_successor_space"
    - "phpdoc_summary"
    - "length_ordered_imports"

finder:
  exclude:
    - "tests"

  name:
    - "*.php"

  not-name:
    - "*blade.php"
